name: Deploy to Google App Engine
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/deploy-appengine@v0
        with:
          credentials: ${{ secrets.gcp_credentials }}
